spring:
  application:
    name: HC-utils
  profiles:
    active: dev
    include: proApiUrl
  jackson:
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      mode: never

server:
  port: 16666

# MyBatis-Plus 公共配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hongchu.pojo.entity
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true

